version: '3.3'

services:
  mongo_db:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
###########################
###########################
###########################
# docker-compose up -d mongo_db
# docker-compose down
